---
title: "Geocoding with sf"
subtitle: "Introduction to Data Science Workshop"
author: "Carlo Greß and Johannes Halkenhäusser"
institute: "Hertie School"
date: "4 November 2021"
output:
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

# Table of contents

<br>

1. [What is geocoding?](#definition)

2. [Geocoding in R](#application)

3. [The **s**imple **f**eatures package in R](#package)

4. [How to use the sf package for geocoding](#howto)

5. [A practical application](#application)

6. [Summary](#summary)

---
class: inverse, center, middle
name: definition

# What is geocoding?

---
# What is geocoding?

- Turning addresses or locations into geographic positions 

- Location of the Hertie School (Friedrichsstraße 180, 10117 Berlin) -> 52.512963808601505, 13.389202140609111

- The geographic position is commonly expressed in **latitude** and **longitude**

  - Latitude refers to the north-south position of a point 

  - Longitude refers to the east-west position of a point

- **Reverse-geocoding** takes given coordinates and translates them into an address

- Both types of geocoding are helpful whenever the location of variables is at the center of attention: 

  - Where do legislators have their offices?
  
  - Where do conservative voters live? 
  
  - Are there geographical patterns in the development of COVID-19 spread?


---
class: inverse, center, middle
name: application

# Geocoding in R

---
# Geocoding in R

- Before starting with the substantial analysis, input data needs to be read in into R

- Geocoding analysis distinguishes between two main input data types: **Relative** and **absolute** input data 

- Relative input data refers to **descriptions** of locations and cannot directly be translated into precise geographic data points

  - Instead, reference locations whose coordinates are known are used for approximation
  
- Absolute input data refers to data that can be directly translated into coordinates

  - Postal addresses and ZIP codes, cities, places
  
- Unsurprisingly, the latter data format is usually desired due to a more intuitive use and higher precision

---
class: inverse, center, middle
name: package

# The **s**imple **f**eatures package in R 

---
# The **s**imple **f**eatures package in R

- Simple features is not limited to the package in R, but rather is a formal standard describing the geographic representation of real-world objects in computers 

- A **feature** commonly relates to such real-world objects, e.g. a street, a city, or a building

- These are represented by several simple features types

- Most common types: points, linestrings, polygons 

- The simple features package in R provides access to the simple feature standard

- It offers multiple functions that are beneficial for working with geodata

  - Calculating surface area or distance, identifying whether a point lays in a given area, creating a point at the centre of an area

---
class: inverse, center, middle
name: howto

# How to use the sf package for geocoding

---
#How to use the sf package for geocoding

- Read in the **input data** (for example, your address or the postal code of your home town) 
- For this purpose, numerous sources as the *Open Street Map* or the Google Maps API can be used
- The build-in `st_read`-command enables users to read in existing datasets and stores them as data.frame

---
class: inverse, center, middle
name: application

# A practical application

---
class: inverse, center, middle
name: summary

# Summary

---